apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: headlamp-oidc
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /homelab/headlamp/azuread-client-id

    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /homelab/headlamp/azuread-client-secret

    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: /homelab/headlamp/azuread-issuer-url

    - secretKey: OIDC_SCOPES
      remoteRef:
        key: /homelab/headlamp/azuread-scopes

    - secretKey: callbackURL
      remoteRef:
        key: /homelab/headlamp/azuread-callback-url