apiVersion: v2
name: external-secrets-wrapper
description: Wrapper chart to install external secrets operator via Helm dependencies
type: application
version: 0.1.0

dependencies:
  - name: external-secrets
    version: 1.3.1
    repository: https://charts.external-secrets.io
