apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rasp-istio-gateway
  namespace: echoserver-ns
spec:
  selector:
    istio: gateway
    app: istio-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
