{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    {{- toYaml .Values.clusterSecretStore.provider | nindent 4 }}
{{- end }}
