apiVersion: v2
name: postgres-operator-wrapper
description: Wrapper chart to install Postgres Operator chart via Helm dependencies
type: application
version: 0.1.0

dependencies:
  - name: cloudnative-pg
    version: 0.27.0
    repository: https://cloudnative-pg.github.io/charts

  