---
apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: alloy
  namespace: alloy
spec:
  controller:
    type: daemonset

  alloy:
    configMap:
      content: |-
        prometheus.remote_write "mimir" {
          endpoint {
            url = "http://mimir-gateway.mimir.svc.cluster.local/api/v1/push"
          }
        }

        prometheus.exporter.self "alloy" {}

        prometheus.scrape "alloy_self" {
          targets         = prometheus.exporter.self.alloy.targets
          scrape_interval = "15s"
          forward_to      = [prometheus.remote_write.mimir.receiver]
        }

        discovery.kubernetes "kube_state_metrics_eps" {
          role = "endpointslice"
        }

        discovery.relabel "kube_state_metrics" {
          targets = discovery.kubernetes.kube_state_metrics_eps.targets

          // namespace do endpointslice
          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            regex         = "prometheus"
            action        = "keep"
          }

          // filtra pelo label kubernetes.io/service-name = prometheus-kube-state-metrics
          rule {
            source_labels = ["__meta_kubernetes_endpointslice_label_kubernetes_io_service_name"]
            regex         = "prometheus-kube-state-metrics"
            action        = "keep"
          }

          // (opcional) porta — vamos deixar SEM filtro primeiro pra validar
          // depois refinamos se você quiser.

          rule {
            target_label = "job"
            replacement  = "kube-state-metrics"
            action       = "replace"
          }
        }

        prometheus.exporter.node "node" {
          procfs_path = "/host/proc"
          sysfs_path  = "/host/sys"
          rootfs_path = "/host/root"
        }

        prometheus.scrape "node" {
          targets         = prometheus.exporter.node.node.targets
          scrape_interval = "30s"
          forward_to      = [prometheus.remote_write.mimir.receiver]
        }

        prometheus.scrape "kube_state_metrics" {
          targets         = discovery.relabel.kube_state_metrics.output
          scrape_interval = "30s"
          forward_to      = [prometheus.remote_write.mimir.receiver]
        }





