apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane-system
type: Opaque
data:
  access-key-id: <Base64EncodedAccessKeyID>
  secret-access-key: <Base64EncodedSecretAccessKey>
---
apiVersion: aws.crossplane.io/v1alpha3
kind: ProviderConfig
metadata:
  name: aws-provider-config
spec:
  credentials:
    secretRef:
      name: aws-credentials
      namespace: crossplane-system
      key: secret-access-key
