apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel
          - --config
          - /etc/cloudflared/config.yaml
          - run
        volumeMounts:
          - name: cloudflared-creds
            mountPath: /etc/cloudflared
            readOnly: true
      volumes:
        - name: cloudflared-creds
          secret:
            secretName: cloudflared-creds
