apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/config-management-plugin: sops
spec:
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  project: k8s-apps
  source:
    repoURL: https://github.com/cassioliveiram/k8s-apps.git
    path: cloudflared
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
