apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-debugger
  namespace: argocd
spec:
  destination:
    namespace: network-debugger
    server: https://kubernetes.default.svc
  project: k8s-apps
  source:
    path: network-debugger
    repoURL: https://github.com/cassioliveiram/k8s-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
