apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-ctrl
  namespace: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi