---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: ds-mimir
spec:
  instanceSelector:
    matchLabels:
      instance: grafana
  datasource:
    name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    url: http://mimir-gateway.observability.svc.cluster.local/prometheus
    isDefault: true
    editable: true