---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: ds-tempo
spec:
  instanceSelector:
    matchLabels:
      instance: grafana
  datasource:
    name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo.tempo.svc.cluster.local:3200
    editable: true
    jsonData:
      httpMethod: GET

      tracesToMetrics:
        datasourceUid: mimir
        spanStartTimeShift: "-2m"
        spanEndTimeShift: "2m"
        tags:
        - key: service.name
          value: service
        - key: service_name
          value: service
        queries:
          - name: "Span rate"
            query: 'sum(rate(traces_spanmetrics_calls_total{service="$service"}[5m]))'
          - name: "Error rate"
            query: 'sum(rate(traces_spanmetrics_calls_total{service="$service",status_code="STATUS_CODE_ERROR"}[5m]))'
          - name: "Latency p95"
            query: 'histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service="$service"}[5m])) by (le))'

      tracesToProfiles:
        datasourceUid: pyroscope
        tags:
          - key: service.name
            value: service
        profileTypeId: "cpu"   # pode trocar depois (cpu, wall, alloc, etc)

