apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
      instance: grafana
spec:
  version: 12.3.1
  config:
    log:
      level: debug
    server:
      domain: "local.cmoreira.dev"
      root_url: "https://local.cmoreira.dev/grafana/"
      serve_from_sub_path: "true"
      protocol: http

    auth:
      disable_login_form: "true"

    auth.generic_oauth:
      enabled: "true"
      name: "Microsoft"
      allow_sign_up: "true"

      client_id: "${GF_AUTH_AZUREAD_CLIENT_ID}"
      client_secret: "${GF_AUTH_AZUREAD_CLIENT_SECRET}"

      scopes: "openid profile email"

      auth_url: "https://login.microsoftonline.com/${GF_AUTH_AZUREAD_TENANT_ID}/oauth2/v2.0/authorize"
      token_url: "https://login.microsoftonline.com/${GF_AUTH_AZUREAD_TENANT_ID}/oauth2/v2.0/token"
      login_attribute_path: preferred_username
      email_attribute_path: preferred_username
      name_attribute_path: name
      allow_assign_grafana_admin: "true"
      role_attribute_path: >
        (preferred_username == 'cassio@cmoreira.dev')
        && 'GrafanaAdmin' || 'Viewer'


  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-azuread
