apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-creds
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: cloudflared-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: cert.pem
      remoteRef:
        key: /homelab/cloudflare/cert-pem
    - secretKey: creds.json
      remoteRef:
        key: /homelab/cloudflare/credentials-json