kube-prometheus-stack:
  defaultRules:
    create: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeEtcd:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: true
    prometheusSpec: 
      retention: 3d
      retentionSize: "5GiB"
      remoteWrite:
      - url: http://mimir-gateway.mimir.svc.cluster.local/api/v1/push