jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update the tag
        uses: julbme/gh-action-manage-tag@v1
        with:
          name: tag-name
          state: present
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
